package com.wellcare.rules;

import com.wellcare.rules.Transaction;
import com.wellcare.rules.RuleMessage;
import java.time.LocalDate;




//Validate Primary Subscriber EME-1-1443
rule "Primary Subscriber Rule"
    dialect "mvel"
	salience 25
	ruleflow-group "PrimaryRules"
    when
        txn : Transaction( subscriberType.toLowerCase() == "y"  )
        
    then
		RuleMessage msg = new RuleMessage();
		msg.setMessageCode("009");
		msg.setMessageText("Primary Rules Executed");
		insert(msg);
			
end

//Validate Primary Subscriber EME-2-1443
rule "Validate Primary Subscriber"
    dialect "mvel"
	salience 30
	ruleflow-group "PrimaryRules"
    when
        txn : Transaction( subscriberType.toLowerCase() != "y")
        
    then
		RuleMessage msg = new RuleMessage();
		msg.setMessageCode("010");
		msg.setMessageText("No primary subscriber found for the transaction");
		insert(msg);
			
end
//Validate Relationship Code EME-1443
rule "Validate Applicant Relationships"
    dialect "mvel"
	salience 20
	ruleflow-group "PrimaryRules"
    when
        txn : Transaction( subscriberType.toLowerCase() == "y" && (relationshipType == null || relationshipType.toLowerCase() != "18") )
        
    then
		RuleMessage msg = new RuleMessage();
		msg.setMessageCode("011");
		msg.setMessageText("Invalid relationship code for the primary subscriber");
		insert(msg);
			
end